config/routes.rb
Rails.application.routes.draw do

  #devise:管理者用
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  #devise:顧客用
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  #publicは表示させない
  scope module: :public do

  #homes
  root to: "homes#top"
  get "about" => "homes#about", as:"about"

  #searches
  get "search" => "searches#search"
  get "/genre/search" => "searches#genre_search"

  #items
  resources :items, only: [:index, :show]

  #cutomers
  get "customers/my_page" => "customers#show"
  get "customers/information/edit" => "customers#edit"
  patch "customers/my_page" => "customers#update", as: :update_customer
  get "customers/unsubscribe" => "customers#unsubscribe"
  patch "customers/withdraw" => "customers#withdraw"

  #cart_items
  resources :cart_items, only: [:index, :update, :create, :destroy] do
    collection do
      delete :destroy_all
    end
  end

  #orders
  resources :orders, only: [:new, :index, :create, :show] do
    collection do
      post :confirm
      get :thanks
    end
  end

  #addresses
  resources :addresses, only: [:index, :edit, :create, :update,:destroy]

  end

  namespace :admin do
    root to: 'homes#top'
    #searches
    get "search" => "searches#search"
    resources :customers,     only: [:index, :show, :edit, :update]
    resources :genres,        only: [:index, :create, :edit, :update, :destroy]
    resources :items,         only: [:index, :show, :create, :edit, :update, :new]
    resources :orders,        only: [:index, :show, :update]
    resources :order_details, only: [:update]

  end
end

app/models/customer.rb
class Customer < ApplicationRecord

  has_many :orders
  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy

  validates :family_name,  :family_name,
                           :first_name,
                           :family_name_kana,
                           :first_name_kana,
                           :email,
                           :encrypted_password,
                           :postcode,
                           :address,
                           :telephone_number,
                           presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #
  def full_name
    family_name + ' ' + first_name
  end

  #カナ
  def full_name_kana
    family_name_kana + '' + first_name_kana
  end

  #会員ステータスの判定
  def cus_status
    if is_active == false
      "退会済会員"
    else
      "現会員"
    end
  end

  #会員ステータスが現会員のみログイン可能
  def active_for_authentication?
    super && (is_active == true)
  end

  # これがないと管理者ログインできないってransackに言われた
  def self.ransackable_attributes(auth_object = nil)
    ["address", "created_at", "email", "encrypted_password", "family_name", "family_name_kana", "first_name", "first_name_kana", "id", "is_active", "postcode", "remember_created_at", "reset_password_sent_at", "reset_password_token", "telephone_number", "updated_at"]
  end

    #ransackに略
  def self.ransackable_associations(auth_object = nil)
    ["addresses", "cart_items", "orders"]
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  def index
    @customers = Customer.page(params[:page]).per(10)
  end

  def show
    @cus = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer)
    else
      render :edit
    end
  end

private

  def customer_params
    params.require(:customer).permit(:family_name,
                                     :first_name,
                                     :family_name_kana,
                                     :first_name_kana,
                                     :email,
                                     :encrypted_password,
                                     :postcode,
                                     :address,
                                     :telephone_number,
                                     :is_active
                                    )
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<%= form_with model: @customer, url: admin_customer_path(@customer) do |f| %>
<%= render "public/shared/error_messages", resource: @customer %>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-10">
      
      <div class="row justify-content-cente">
        <div class="col-lg-1"></div><!--レイアウト調整のための空col-->
        <div class="col-sm-auto">
          <h3 class="bg-light mb-4">　<%= @customer.full_name %>さんの会員情報編集　</h3>
        </div>
      </div>
      
      <div class="row justify-content-center">
      <!--1行目-->
        <div class="col-lg-2 col-md-4 col-sm-4 my-3">
          <p class="mt-1 mb-3">会員ID</p>
          <p class="my-4">氏名</p>
          <p class="my-4">フリガナ</p>
          <p class="my-4 pt-1">郵便番号</p>
          <p class="my-4 pt-2">住所</p>
          <p class="my-4 pt-2">電話番号</p>
          <p class="my-4 pt-1">メールアドレス</p>
          <p class="my-4">会員ステータス</p>
        </div>
        <!--2行目-->
        <div class="col-4 my-3">
          <p><%= @customer.id %></p>
          
            <div class="form-group">
              <%= f.text_field :family_name, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= f.text_field :family_name_kana, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= f.text_field :postcode, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= f.text_field :address, class: "form-control", style:"width: 200%;" %>
            </div>
            <div class="form-group">
              <%= f.text_field :telephone_number, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= f.text_field :email, class: "form-control" %>
            </div>
            
            <div class="row">
              <div class="col-6">
                <%= f.radio_button :is_active, true %>
                <%= f.label :is_active_true, "有効" %>
              </div>
              <div class="col-6">
                <%= f.radio_button :is_active, false %>
                <%= f.label :is_active_false, "退会" %>
              </div>
            </div>
            
            <%= f.submit '変更を保存', class: "btn btn-success btn-block mt-3" %>
          </div>
          
          <!--3行目-->
          <div class="col-4 mt-5 mb-3">
            <div></div>
            <div class="form-group mt-2">
              <%= f.text_field :first_name, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= f.text_field :first_name_kana, class: "form-control" %>
            </div>
          </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12 col-md-10">
      <div class="d-flex justify-content-top mb-3">
        <h3 class="bg-light p-2">会員一覧</h3>
      </div>
      <table class="table">
        <thead class="thead-light">
          <tr>
            <th>会員ID</th>
            <th>氏名</th></th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody class="table-hover">
          <% @customers.each do |customer| %>
            <tr>
              <td><%= customer.id %></td>
              <td>
                <%= link_to admin_customer_path(customer), class:"edit-link" do %>
                  <%= customer.full_name %>
                <% end %>
              </td>
              <td><%= customer.email %></td>
              <!--Customerモデルで設定したメソッドを使う形に変更しました（渡邊）-->
              <td>
                <% if customer.is_active? %>
                  <span class="text-success font-weight-bold"><%= customer.cus_status %></span>
                <% else %>
                  <span class="text-secondary font-weight-bold"><%= customer.cus_status %></span>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <%= paginate @customers %>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-10">

      <div class="row justify-content-center">

        <div class="col-lg-2"></div><!--colを改行させるための空col-->
        <div class="col-sm-auto">
          <h3 class="bg-light mb-3">　<%= @cus.full_name %>さんの会員詳細　</h3>
        </div>
        <div class="col-lg-4 col-md-5 col-sm-3 col-xs-3"></div><!--colを改行させるための空col-->

        <div class="col-xs-4 my-3 mr-5">
          <p>会員ID</p>
          <p>氏名</p>
          <p>フリガナ</p>
          <p>郵便番号</p>
          <p>住所</p>
          <p>電話番号</p>
          <p>メールアドレス</p>
          <p>会員ステータス</p>
        </div>

        <div class="col-xs-5 my-3">
          <p><%= @cus.id %></p>
          <p><%= @cus.full_name %></p>
          <p><%= @cus.full_name_kana %></p>
          <p><%= @cus.postcode %></p>
          <p><%= @cus.address %></p>
          <p><%= @cus.telephone_number %></p>
          <p><%= @cus.email %></p>
          <% if @cus.is_active? %>
            <p class="text-success font-weight-bold"><%= @cus.cus_status %></p>
          <% else %>
            <p class="text-secondary font-weight-bold"><%= @cus.cus_status %></p>
          <% end %>

          <button class="btn">
            <%= link_to '編集する', edit_admin_customer_path(@cus), class: "btn btn-success" %>
          </button>
          <button class="btn">
            <%= link_to '注文履歴一覧を見る', admin_orders_path(customer_id: @cus.id), class: "btn btn-primary" %>
          </button>

        </div>
      </div>
    </div>
  </div>
</div>