config/routes.rb
Rails.application.routes.draw do

  #devise:管理者用
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  #devise:顧客用
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  #publicは表示させない
  scope module: :public do

  #homes
  root to: "homes#top"
  get "about" => "homes#about", as:"about"

  #searches
  get "search" => "searches#search"
  get "/genre/search" => "searches#genre_search"

  #items
  resources :items, only: [:index, :show]

  #cutomers
  get "customers/my_page" => "customers#show"
  get "customers/information/edit" => "customers#edit"
  patch "customers/my_page" => "customers#update", as: :update_customer
  get "customers/unsubscribe" => "customers#unsubscribe"
  patch "customers/withdraw" => "customers#withdraw"

  #cart_items
  resources :cart_items, only: [:index, :update, :create, :destroy] do
    collection do
      delete :destroy_all
    end
  end

  #orders
  resources :orders, only: [:new, :index, :create, :show] do
    collection do
      post :confirm
      get :thanks
    end
  end

  #addresses
  resources :addresses, only: [:index, :edit, :create, :update,:destroy]

  end

  namespace :admin do
    root to: 'homes#top'
    #searches
    get "search" => "searches#search"
    resources :customers,     only: [:index, :show, :edit, :update]
    resources :genres,        only: [:index, :create, :edit, :update, :destroy]
    resources :items,         only: [:index, :show, :create, :edit, :update, :new]
    resources :orders,        only: [:index, :show, :update]
    resources :order_details, only: [:update]

  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details, dependent: :destroy
  has_many :items, through: :order_details
  belongs_to :customer
  
  validates :customer_id,    presence: true
  validates :name,           presence: true
  validates :postcode,       presence: true
  validates :address,        presence: true
  validates :shipping_fee,   presence: true
  validates :total_payment,  presence: true
  validates :payment_method, presence: true
  validates :status,         presence: true

  def which_pay
    case self.payment_method
    when 0 then
      "クレジットカード"
    when 1 then
      "銀行振込"
    end
  end

  #enum支払い
  enum payment_method: {
    credit_card: 0,
    bank_transfer: 1
  }

  #enum注文
  enum status: {
    waiting: 0,
    paid_up: 1,
    making: 2,
    preparing: 3,
    shipping: 4
  }

  def my_status
    case self.status
    when 0 then
      "入金待ち"
    when 1 then
      "入金確認"
    when 2 then
      "製作中"
    when 3 then
      "発送準備中"
    when 4 then
      "発送済み"
    end
  end

  #注文時間（年/月/日）
  def y_to_d
    self.created_at.strftime('%Y/%m/%d')
  end

  # 注文時間（年/月/日 時間:分:秒）
  def y_to_s
    self.created_at.strftime('%Y/%m/%d %H:%M:%S')
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @od = Order.find(params[:id])
    @ols = @od.order_details
    @total = @ols.sum(&:sum)
    @bill = @total + @od.shipping_fee
  end

  def index
    @customer = Customer.find(params[:customer_id])
    @orders = @customer.orders.page(params[:page]).per(10)
  end

  def update
    @order = Order.find(params[:id])
    new_status = params[:order][:status]

    @order.update(params_order)

  if new_status == "paid_up" # 注文ステータスが「入金確認」
    @order.order_details.update_all(making_status: :waiting) # すべての製作ステータスを「製作待ち」に更新
  elsif new_status != "shipping" && @order.order_details.all? { |ol| ol.making_status == "making_completed" } # 全ての製作ステータスが「製作完了」かつ新しい注文ステータスが「発送完了」でない場合
    @order.update(status: :preparing) # 注文ステータスを「発送準備中」に更新
  elsif @order.order_details.any? { |ol| ol.making_status == "making" } # 製作ステータスに「製作中」が含まれている場合
    @order.update(status: :making) # 注文ステータスを「製作中」に更新
  end

    redirect_to admin_order_path(@order)
  end

  private

  def params_order
    params.require(:order).permit(:customer_id,
                                  :name,
                                  :postcode,
                                  :address,
                                  :shipping_fee,
                                  :total_payment,
                                  :payment_method,
                                  :status
                                  )
  end


end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12 col-md-10">
      <div class="d-flex justify-content-top mb-3">
        <h3 class="bg-light text-center w-fit-content p-2"><%= @customer.full_name %>さんの注文履歴</h3>
      </div>
      <table class="table">
        <thead class="thead-light">
          <tr>
            <th>購入日時</th>
            <th>注文個数</th>
            <th>注文ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @orders.each do |order| %>
            <tr>
              <td>
                <%= link_to admin_order_path(order), class:"edit-link" do %>
                  <%= order.y_to_s %>
                <% end %>
              </td>
              <td><%= order.order_details.sum(&:amount) %></td>
              <td><%= I18n.t("enums.order.status.#{order.status}") %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @orders %>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12 col-md-10">
      <div class="d-flex justify-content-top mb-3">
        <h3 class="bg-light text-center w-fit-content p-2">注文履歴詳細</h3>
      </div>
    </div>
  </div>

  <!--購入者情報-->
  <div class="row">
    <div class="col">
      <table>
        <thead>
          <tr>
            <th><strong>購入者</strong></th>
            <td>
              　<%= link_to @od.customer.full_name, admin_orders_path(:customer_id => @od.customer.id), class:"edit-link" %>
          　</td>
          </tr>

          <tr>
            <th><strong>注文日</strong></th>
            <td>　<%= @od.y_to_d%></td>
          </tr>

          <tr>
            <th><strong>配送先</strong></th>
            <td>
              　〒<%= @od.postcode %> <%= @od.address %><br>
              　<%= @od.name %>
            </td>
          </tr>

          <tr>
            <th><strong>支払方法</strong></th>

            <td>　<%= I18n.t("enums.order.payment_method.#{@od.payment_method}") %></td>

          </tr>

          <tr>
            <th><strong>注文ステータス</strong></th>
            <td>
              <%= form_with model: @od, url: admin_order_path, method: :patch, local: true do |f| %>
                　<%= f.select :status, Order.statuses.keys.map { |status| [I18n.t("enums.order.status.#{status}"), status] } %>
                <%= f.submit "更新",class:"ml-4 btn btn-success" %>
              <% end %>
            </td>
          </tr>
        </thead>
      </table>
    </div>
  </div>

  <!--商品情報-->
  <div class="row mt-3">
    <!--注文詳細テーブル-->
    <div class="col-lg-9 col-sm-12">
      <table class="table">
        <thead class="thead-light">
          <tr>
            <th>商品名</th>
            <th>単価（税込）</th>
            <th>数量</th>
            <th>小計</th>
            <th>製作ステータス</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @ols.each do |ol| %>
            <tr>
              <td><%= ol.item.name %></td>
              <td><%= ol.item.taxed_price.to_s(:delimited) %></td>
              <td><%= ol.amount %></td>
              <td><%= ol.sum.to_s(:delimited) %></td>
              <%= form_with model: ol, url: admin_order_detail_path, method: :patch, local: true do |f| %>
                <td>
                  <%= f.select :making_status, OrderDetail.making_statuses.keys.map { |status| [I18n.t("enums.order_details.making_status.#{status}"), status] } %>
                  <%= f.hidden_field :order_detail_id, :value => ol.id %>
                </td>
                <td>
                  <%= f.submit "更新", class:"btn btn-success x-0" %>
                </td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <!--金額テーブル-->
    <div class="col-lg-3 col-10 mt-auto mb-3">
      <table>
        <thead>
          <tr>
            <th>商品合計</th>
            <td>　<%= @total.to_s(:delimited) %>円</td>
          </tr>
          <tr>
            <th>送料</th>
            <td class="text-right">　<%= @od.shipping_fee.to_s(:delimited) %>円</td>
          </tr>
          <tr>
            <th>請求金額合計</th>
            <td>　<%= @bill.to_s(:delimited) %>円</td>
          </tr>
        </thead>
      </table>
    </div>
  </div>

</div>