config/routes.rb
Rails.application.routes.draw do

  #devise:管理者用
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  #devise:顧客用
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  #publicは表示させない
  scope module: :public do

  #homes
  root to: "homes#top"
  get "about" => "homes#about", as:"about"

  #searches
  get "search" => "searches#search"
  get "/genre/search" => "searches#genre_search"

  #items
  resources :items, only: [:index, :show]

  #cutomers
  get "customers/my_page" => "customers#show"
  get "customers/information/edit" => "customers#edit"
  patch "customers/my_page" => "customers#update", as: :update_customer
  get "customers/unsubscribe" => "customers#unsubscribe"
  patch "customers/withdraw" => "customers#withdraw"

  #cart_items
  resources :cart_items, only: [:index, :update, :create, :destroy] do
    collection do
      delete :destroy_all
    end
  end

  #orders
  resources :orders, only: [:new, :index, :create, :show] do
    collection do
      post :confirm
      get :thanks
    end
  end

  #addresses
  resources :addresses, only: [:index, :edit, :create, :update,:destroy]

  end

  namespace :admin do
    root to: 'homes#top'
    #searches
    get "search" => "searches#search"
    resources :customers,     only: [:index, :show, :edit, :update]
    resources :genres,        only: [:index, :create, :edit, :update, :destroy]
    resources :items,         only: [:index, :show, :create, :edit, :update, :new]
    resources :orders,        only: [:index, :show, :update]
    resources :order_details, only: [:update]

  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
  validates :name, presence: true, uniqueness: true
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      if request.referer == new_admin_item_url
        flash[:notice] = "ジャンルを追加しました。"
        redirect_to request.referer
      else
        flash[:notice] = "ジャンルを追加しました。"
        redirect_to admin_genres_path
      end
    else
      @genres = Genre.all
      flash.now[:alert] ="ジャンルを追加できませんでした。"
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render :edit
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
  
  <div class="row">
    <div class="col-5">
      <h3 class="bg-light">ジャンル編集</h3>
    </div>
  </div>
  
  <%= form_with model: @genre, url: admin_genre_path, method: :patch do |f| %>
    <div class="row mt-5">
      <div class="form-group col-lg-2 col-3">
        <%= f.label :name, "ジャンル名" %>
      </div>
      <div class="form-group col-lg-3 col-5">
        <%= f.text_field :name, placeholder: "ジャンル名", autofocus: true, style:"width: 100%" %>
      </div>
      <div class="form-group col-lg-2 col-3">
        <%= f.submit "変更を保存", class:"btn btn-success btn-block" %>
      </div>
    </div>
  <% end %>
    
    
  </div>
    
</div>

app/views/admin/genres/index.html.erb
<div class="container">

  <!--タイトル-->
  <div class="row">
    <div class="col-7">
      <div class="d-flex justify-content-top">
        <h3 class="bg-light text-center w-fit-content p-2">ジャンル一覧・追加</h3>
      </div>
    </div>
  </div>

  <!--ジャンル追加-->
  <%= form_with model: Genre.new, url: admin_genres_path do |f| %>
    <div class="row mt-5">
      <div class="col-lg-2 col-3">
        <%= f.label :name, "ジャンル名" %>
      </div>
      <div class="col-lg-3 col-5">
        <%= f.text_field :name, placeholder: "ジャンル名", style:"width: 100%" %>
      </div>
      <div class="col-lg-2 col-3">
        <%= f.submit "新規登録", class:"btn btn-success btn-block" %>
      </div>
    </div>
  <% end %>

  <!--ジャンル一覧-->
  <div class="row mt-5">
    <div class="col-lg-4 col-7">
      <table class="table">
        <thead class="thead-light">
          <tr>
            <th class="font-kosugi">　　ジャンル</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @genres.each do |genre| %>
            <tr>
              <td>
                <%= genre.name %>
              </td>
              <td>
                <%= link_to '編集する', edit_admin_genre_path(genre), class:"btn btn-success" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>


</div>