config/routes.rb
Rails.application.routes.draw do

  #devise:管理者用
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  #devise:顧客用
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  #publicは表示させない
  scope module: :public do

  #homes
  root to: "homes#top"
  get "about" => "homes#about", as:"about"

  #searches
  get "search" => "searches#search"
  get "/genre/search" => "searches#genre_search"

  #items
  resources :items, only: [:index, :show]

  #cutomers
  get "customers/my_page" => "customers#show"
  get "customers/information/edit" => "customers#edit"
  patch "customers/my_page" => "customers#update", as: :update_customer
  get "customers/unsubscribe" => "customers#unsubscribe"
  patch "customers/withdraw" => "customers#withdraw"

  #cart_items
  resources :cart_items, only: [:index, :update, :create, :destroy] do
    collection do
      delete :destroy_all
    end
  end

  #orders
  resources :orders, only: [:new, :index, :create, :show] do
    collection do
      post :confirm
      get :thanks
    end
  end

  #addresses
  resources :addresses, only: [:index, :edit, :create, :update,:destroy]

  end

  namespace :admin do
    root to: 'homes#top'
    #searches
    get "search" => "searches#search"
    resources :customers,     only: [:index, :show, :edit, :update]
    resources :genres,        only: [:index, :create, :edit, :update, :destroy]
    resources :items,         only: [:index, :show, :create, :edit, :update, :new]
    resources :orders,        only: [:index, :show, :update]
    resources :order_details, only: [:update]

  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  validates :name, :address, presence: true
  validates :address, length: { maximum: 50 }
  validates :postcode, format: {with: /\A\d{7}\z/}, presence: true

  def mark_postcode
    "〒" + postcode
  end

  # order.new.htmlのセレクトボックスで送り先を表示するためのメソッド
  def address_display
    '〒' + postcode + ' ' + address + ' ' + name
  end 
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  
  # 税込み価格×個数で小計を算出
  def sum
    item.taxed_price * amount
  end 
  
  # カート内商品の最大表示数。10個を超える場合はamount、超えない場合は10を表示
  def variable
    if self.amount > 10
      self.amount
    else
      10
    end 
  end
  
end

app/models/customer.rb
class Customer < ApplicationRecord

  has_many :orders
  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy

  validates :family_name,  :family_name,
                           :first_name,
                           :family_name_kana,
                           :first_name_kana,
                           :email,
                           :encrypted_password,
                           :postcode,
                           :address,
                           :telephone_number,
                           presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #
  def full_name
    family_name + ' ' + first_name
  end

  #カナ
  def full_name_kana
    family_name_kana + '' + first_name_kana
  end

  #会員ステータスの判定
  def cus_status
    if is_active == false
      "退会済会員"
    else
      "現会員"
    end
  end

  #会員ステータスが現会員のみログイン可能
  def active_for_authentication?
    super && (is_active == true)
  end

  # これがないと管理者ログインできないってransackに言われた
  def self.ransackable_attributes(auth_object = nil)
    ["address", "created_at", "email", "encrypted_password", "family_name", "family_name_kana", "first_name", "first_name_kana", "id", "is_active", "postcode", "remember_created_at", "reset_password_sent_at", "reset_password_token", "telephone_number", "updated_at"]
  end

    #ransackに略
  def self.ransackable_associations(auth_object = nil)
    ["addresses", "cart_items", "orders"]
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
  validates :name, presence: true, uniqueness: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image

  has_many :cart_items, dependent: :destroy
  has_many :order_details

  belongs_to :genre

  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
  validates :is_active, inclusion: [true, false]

  #販売ステータスを日本語で表示
  def sale_status
    if is_active == true
      "販売中"
    else
      "販売停止中"
    end
  end

  #税込価格
  def taxed_price
    (self.price * 1.10).round
  end

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join("app/assets/images/sato.cake/皿にケーキ.jpg")
      image.attach(io: File.open(file_path), filename: "default-image.jpg", content_type: "image/*")
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  #ransackに書けって言われた
  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "genre_id", "id", "introduction", "is_active", "name", "price", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["cart_items", "genre", "image_attachment", "image_blob", "order_details"]
  end

end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details, dependent: :destroy
  has_many :items, through: :order_details
  belongs_to :customer
  
  validates :customer_id,    presence: true
  validates :name,           presence: true
  validates :postcode,       presence: true
  validates :address,        presence: true
  validates :shipping_fee,   presence: true
  validates :total_payment,  presence: true
  validates :payment_method, presence: true
  validates :status,         presence: true

  def which_pay
    case self.payment_method
    when 0 then
      "クレジットカード"
    when 1 then
      "銀行振込"
    end
  end

  #enum支払い
  enum payment_method: {
    credit_card: 0,
    bank_transfer: 1
  }

  #enum注文
  enum status: {
    waiting: 0,
    paid_up: 1,
    making: 2,
    preparing: 3,
    shipping: 4
  }

  def my_status
    case self.status
    when 0 then
      "入金待ち"
    when 1 then
      "入金確認"
    when 2 then
      "製作中"
    when 3 then
      "発送準備中"
    when 4 then
      "発送済み"
    end
  end

  #注文時間（年/月/日）
  def y_to_d
    self.created_at.strftime('%Y/%m/%d')
  end

  # 注文時間（年/月/日 時間:分:秒）
  def y_to_s
    self.created_at.strftime('%Y/%m/%d %H:%M:%S')
  end

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

    # 税込み価格×個数で小計を算出
  def sum
    item.taxed_price * amount
  end
  
  #enum製作
  enum making_status: {
    impossible: 0,
    waiting: 1,
    making: 2,
    making_completed: 3
  }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  def top
    @orders = Order.page(params[:page]).per(10)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_admin!, if: :admin_area?
  before_action :set_search

  def set_search
    if admin_signed_in?
      @p = Customer.ransack(params[:q])
      @search = @p.result(distinct: true)
    else
      @q = Item.ransack(params[:q])
      @search = @q.result(distinct: true)
    end
      @result = params[:q]&.values&.reject(&:blank?)
  end

private

  def admin_area?
    request.fullpath.include?("/admin") && !request.fullpath.include?("/admin/sign_in")
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_flash.html.erb
<div class="row justify-content-center font-weight-bold" style="background-color: #b0ffc5; color: #005b0d">
  <%= flash[:notice] %>
</div>
<div class="row justify-content-center bg-danger text-light">
  <%= flash[:alert] %>
</div>

app/views/layouts/_footer.html.erb
<footer class="mt-4" style="height: 100px; background-color: #0e357f;">
  <div style="height: 10px; background-color: #f9bb02;"></div>
  <div class="container">
    <div class="row justify-content-center align-items-center" style="height: 90px;">
      <p class="text-white font-formal">©NaganoCake</p>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="mb-3">
  <nav class="navbar navbar-expand-lg navbar-dark " style="background-color: #0e357f;">
    <div class="container" style="position: relative">
      <a class="navbar-brand" href="/">
        <%= image_tag src="sato.cake/logo_transparent_orange_cccp10", size: '100x80' %>
      </a>
      <% if customer_signed_in? %>
        <p class="text-light" style="position: absolute; left: 40%; top: 30px">ようこそ、<%= current_customer.full_name %>さん！</p>
      <% end %>
      <button class="navbar-toggler openbtn" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <!--<span class="navbar-toggler-icon"></span>-->
        <span></span><span></span><span></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav mr-auto font-formal gnavi">
        </ul>
        <!--ul-2を適用すれば、画面幅991px以下において、下線の長さが文字と同じくらいになる。-->
        <ul class="navbar-nav gnavi ul- font-formal" style="">

          <% if admin_signed_in? %>
          <!--管理者ログイン後-->
            <li>
              <%= link_to admin_items_path,class: 'nav-link text-light a' do %>
                <i class="fa-solid fa-cake-candles"></i> 商品一覧
              <% end %>
            </li>
            <li>
              <%=  link_to admin_customers_path,class: 'nav-link text-light a' do %>
                <i class="fas fa-users"></i> 会員一覧
              <% end %>
            </li>
            <li>
              <%= link_to admin_root_path, class: 'nav-link text-light a' do %>
                <i class="fa-solid fa-clock-rotate-left"></i> 注文履歴一覧
              <% end %>
            </li>
            <li>
              <%=  link_to admin_genres_path ,class: 'nav-link text-light a' do %>
                <i class="fa-solid fa-image"></i> ジャンル一覧
              <% end %>
            </li>
            <li>
              <%= link_to destroy_admin_session_path, class: 'nav-link text-light a', method: :delete do %>
               <i class="fa-solid fa-right-from-bracket"></i> ログアウト
              <% end %>
            </li>
          <% elsif customer_signed_in? %>
          <!--サインイン後-->
            <li>
              <%= link_to customers_my_page_path(current_customer), class: 'nav-link text-light a' do %>
                <i class="fa-solid fa-user"></i> マイページ
              <% end %>
            </li>
            <li>
              <%= link_to items_path,class: 'nav-link text-light a' do %>
                <i class="fa-solid fa-cake-candles"></i> 商品一覧
              <% end %>
            </li>
            <li>
              <%= link_to cart_items_path, class: 'nav-link text-light a' do %>
               <i class="fa-solid fa-cart-shopping"></i> カート
              <% end %>
            </li>
            <li>
              <%= link_to destroy_customer_session_path, method: :delete,class: 'nav-link text-light a' do %>
                <i class="fas fa-sign-out-alt"></i> Log out
              <% end %>
            </li>
          <% else %>
          <!--サインアウト後-->
            <li>
              <%= link_to about_path,class: 'nav-link text-light a' do %>
                <i class="fas fa-link"></i> About
              <% end %>
            </li>
            <li>
              <%= link_to items_path,class: 'nav-link text-light a' do %>
                <i class="fa-solid fa-cake-candles"></i> 商品一覧
              <% end %>
            </li>
            <li>
              <%= link_to new_customer_registration_path,class: 'nav-link text-light a' do %>
                <i class="fas fa-user-plus"></i> 新規登録
              <% end %>
            </li>
            <li>
              <%= link_to new_customer_session_path ,class: 'nav-link text-light a' do %>
                <i class="fas fa-sign-in-alt"></i> ログイン
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>

    <div class="mx-auto mt-3">
      <%= render "layouts/search", q: @q %>
    </div>

  </nav>
  <div style="height: 10px; background-color: #f9bb02"></div>
  <%= render "layouts/flash" %>
</header>

app/views/layouts/_search.html.erb
<% if admin_signed_in? %>
   <%= search_form_for @p, url: admin_search_path do |cus| %>
      <div class="form-inline">
         <%= cus.search_field :family_name_or_first_name_or_family_name_kana_or_first_name_kana_cont, class: "form-control", placeholder: 'Search' %>
         <%= button_tag type: "submit", class: "btn btn-primary" do %>
            <i class="fas fa-search"></i>
         <% end %>
      </div>
   <% end %>
<% else %>
   <%= search_form_for @q, url: search_path do |f| %>
      <div class="form-inline">
         <%= f.search_field :name_cont, class: "form-control", placeholder: 'Search' %>
         <%= button_tag type: "submit", class: "btn btn-primary" do %>
            <i class="fas fa-search"></i>
         <% end %>
      </div>
   <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCAKE</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="icon" href="/favicon.png" type="image/png">
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1">
    <script src="https://kit.fontawesome.com/170e4c3b0b.js" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/canvas-confetti@1.3.2/dist/confetti.browser.min.js"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="footerFixed">
      <%= render 'layouts/header' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>

  </body>
</html>